import {ArrowLeft,ArrowRight,CheckCircle2,Heart,MapPin,Share2,ShieldCheck,Users} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import educate from '../../educate.jpg';import feed from '../../feed.jpg';import environment from '../../environment.jpg';import wellness from '../../Wellness.jpg';import clinic from '../../Clinic.jpg';
const campaigns={
'keep-a-child-in-school':{title:'Keep a child in school',cat:'Education',location:'Nairobi',raised:182500,goal:300000,donors:84,image:educate,desc:'Books, uniforms and learning materials for students who need a stronger start.',about:'Every child deserves the chance to learn without basic school supplies becoming a barrier. This campaign supports students with books, uniforms and essential learning materials.',uses:['School books and learning materials','Uniforms and essential supplies','Direct support for students in need']},
'a-clinic-for-the-community':{title:'A clinic for the community',cat:'Healthcare',location:'Kisumu',raised:412000,goal:500000,donors:156,image:clinic,desc:'Essential healthcare and maternal support closer to families.',about:'The community clinic campaign helps bring essential healthcare and maternal support closer to families who face long journeys for basic services.',uses:['Essential medical supplies','Maternal health support','Community health outreach']},
'meals-for-500-families':{title:'Meals for 500 families',cat:'Food',location:'Nairobi',raised:97500,goal:150000,donors:62,image:feed,desc:'A community-led food drive providing nutritious meals this month.',about:'This community-led food drive provides nutritious meals to families facing food insecurity and helps local volunteers turn donations into direct support.',uses:['Nutritious food packages','Community meal distribution','Local volunteer logistics']},
'restore-our-local-forest':{title:'Restore our local forest',cat:'Environment',location:'Kiambu',raised:64000,goal:120000,donors:41,image:environment,desc:'Plant native trees and protect a vital green space for future generations.',about:'The project restores a local forest with native trees and community stewardship, protecting a vital green space for future generations.',uses:['Native tree seedlings','Forest restoration days','Community conservation activities']},
'digital-skills-for-teens':{title:'Digital skills for teens',cat:'Education',location:'Mombasa',raised:210000,goal:250000,donors:97,image:'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1400&q=85',desc:'Practical technology and career skills for young people.',about:'Young people need practical digital skills to access education and future opportunities. This initiative provides hands-on technology and career training.',uses:['Training sessions','Learning devices and materials','Career-readiness activities']},
'mental-wellness-outreach':{title:'Mental wellness outreach',cat:'Healthcare',location:'Nairobi',raised:138000,goal:200000,donors:73,image:wellness,desc:'Safe spaces and counselling sessions for young people.',about:'This initiative creates safe spaces and accessible support for young people through community wellness outreach.',uses:['Wellness sessions','Safe community spaces','Youth support activities']}}
export default function Campaign(){const {slug}=useParams();const c=campaigns[slug];if(!c)return <main className="campaign-not-found"><h1>Campaign not found</h1><Link className="primary" to="/">Back to campaigns</Link></main>;const pct=Math.min(100,Math.round(c.raised/c.goal*100));const share=async()=>{const url=window.location.href;try{await navigator.share({title:c.title,text:`Support ${c.title} through KVD.`,url})}catch{await navigator.clipboard?.writeText(url)}};return <div className="campaign-page"><header className="campaign-nav"><Link className="brand" to="/"><span className="logo"><Heart size={16} fill="currentColor"/></span><span>KVD<small>Kindred Vince Donations</small></span></Link><Link className="secondary" to="/"><ArrowLeft size={15}/> Back</Link></header><main><div className="campaign-hero"><img src={c.image} alt={c.title}/><div className="campaign-hero-copy"><span className="pill"><ShieldCheck size={14}/> Verified campaign</span><div className="campaign-location"><MapPin size={14}/>{c.location} · {c.cat}</div><h1>{c.title}</h1><p>{c.desc}</p><div className="campaign-actions"><Link className="primary" to={`/?donate=${slug}`}>Donate now <ArrowRight size={16}/></Link><button className="secondary" onClick={share}><Share2 size={16}/> Share</button></div></div></div><section className="campaign-detail-grid"><article className="campaign-content"><span className="eyebrow">ABOUT THIS CAMPAIGN</span><h2>Make a direct difference.</h2><p>{c.about}</p><h3>How your contribution helps</h3><div className="use-list">{c.uses.map(x=><div key={x}><CheckCircle2 size={17}/><span>{x}</span></div>)}</div><div className="trust-panel"><ShieldCheck size={20}/><div><strong>Verified by KVD</strong><p>Campaign information is reviewed before fundraising is activated.</p></div></div></article><aside className="campaign-donation-card"><span className="eyebrow">CAMPAIGN PROGRESS</span><div className="big-amount">KES {c.raised.toLocaleString()}</div><div className="goal">of KES {c.goal.toLocaleString()} goal</div><div className="bar"><i style={{width:`${pct}%`}}/></div><div className="progress-row"><strong>{pct}% funded</strong><span>{c.donors} supporters</span></div><Link className="primary full" to={`/?donate=${slug}`}>Support this campaign <ArrowRight size={16}/></Link><div className="secure-note"><ShieldCheck size={14}/> Secure M-Pesa donation · No account required</div></aside></section></main></div>}
