import {useState} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {ArrowRight,Eye,EyeOff,Heart,ShieldCheck,Sparkles} from 'lucide-react';
import {useAuth} from '../auth/AuthContext';
import '../login.css';

export default function Login(){
 const {login}=useAuth();const nav=useNavigate();const loc=useLocation();
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [showPassword,setShowPassword]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 const submit=async e=>{e.preventDefault();setError('');setNotice('');setBusy(true);try{await login(email,password);nav(loc.state?.from?.pathname||'/dashboard',{replace:true})}catch(x){setError(x.message)}finally{setBusy(false)}};
 const forgot=()=>{setError('');setNotice(email?`Password reset instructions will be sent to ${email}. Password recovery will be connected to the backend.`:'Enter your email address first, then select Forgot password.');};
 return <main className="auth-page login-page"><div className="auth-shell">
  <section className="auth-showcase" aria-hidden="true"><Link className="brand auth-brand" to="/"><span className="logo"><Heart size={16} fill="currentColor"/></span><span>Kindred Vince Donations<small>KVD · Give with purpose</small></span></Link><div className="showcase-copy"><span className="auth-pill"><Sparkles size={14}/> Giving with purpose</span><h2>Welcome back.<br/><em>Your impact is waiting.</em></h2><p>Continue supporting causes, track your giving and stay connected to the communities you care about.</p><div className="showcase-stat"><strong>18.4M+</strong><span>KES raised through KVD</span></div></div><div className="showcase-orb one"/><div className="showcase-orb two"/></section>
  <section className="auth-card" aria-labelledby="login-title"><div className="mobile-auth-brand"><Link className="brand" to="/"><span className="logo"><Heart size={16} fill="currentColor"/></span><span>Kindred Vince Donations<small>KVD · Give with purpose</small></span></Link></div><div className="auth-heading"><span className="eyebrow">WELCOME BACK</span><h1 id="login-title">Sign in to KVD</h1><p>Manage your donations, campaigns and community impact.</p></div>{error&&<div className="form-error" role="alert">{error}</div>}{notice&&<div className="form-success" role="status">{notice}</div>}<form onSubmit={submit}><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" placeholder="you@example.com" inputMode="email"/></label><label>Password<span className="password-wrap"><input type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password" placeholder="Enter your password"/><button type="button" className="password-toggle" aria-label={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label><div className="form-row"><label className="remember"><input type="checkbox"/><span>Remember me</span></label><button type="button" className="forgot" onClick={forgot}>Forgot password?</button></div><button className="primary full auth-submit" disabled={busy}>{busy?<><span className="spinner"/> Signing in…</>:<>Sign in <ArrowRight size={16}/></>}</button></form><div className="auth-note"><ShieldCheck size={17}/><span><strong>Secure account</strong><small>Your credentials are protected by KVD authentication.</small></span></div><p className="switch">New to KVD? <Link to="/register">Create an account</Link></p><Link className="back-home" to="/">← Back to homepage</Link></section>
 </div></main>;
}
