import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Heart,Search,Sun,Moon,ShieldCheck,ArrowRight,Menu,X,Users,TrendingUp,HandHeart,MapPin,Receipt,LayoutDashboard} from 'lucide-react';
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import './styles.css';

const campaigns=[
{id:1,category:'Education',title:'Keep a child in school',location:'Nairobi',raised:182500,goal:300000,donors:84,days:18,desc:'Books, uniforms and learning materials for students who need a stronger start.'},
{id:2,category:'Healthcare',title:'A clinic for the community',location:'Kisumu',raised:412000,goal:500000,donors:156,days:11,desc:'Essential healthcare and maternal support closer to families.'},
{id:3,category:'Food',title:'Meals for 500 families',location:'Nairobi',raised:97500,goal:150000,donors:62,days:8,desc:'A community-led food drive providing nutritious meals this month.'},
{id:4,category:'Environment',title:'Restore our local forest',location:'Kiambu',raised:64000,goal:120000,donors:41,days:26,desc:'Plant native trees and protect a vital green space for future generations.'},
{id:5,category:'Education',title:'Digital skills for teens',location:'Mombasa',raised:210000,goal:250000,donors:97,days:14,desc:'Practical technology and career skills for young people.'},
{id:6,category:'Healthcare',title:'Mental wellness outreach',location:'Nairobi',raised:138000,goal:200000,donors:73,days:21,desc:'Safe spaces and counselling sessions for young people.'}
];
const chart=[{month:'Jan',amount:1.8},{month:'Feb',amount:2.4},{month:'Mar',amount:3.1},{month:'Apr',amount:4.2},{month:'May',amount:3.7},{month:'Jun',amount:5.1}];
const kes=n=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:0}).format(n);
function App(){
 const [filter,setFilter]=useState('All'); const [search,setSearch]=useState(''); const [dark,setDark]=useState(localStorage.getItem('kvd-theme')==='dark'); const [menu,setMenu]=useState(false); const [donate,setDonate]=useState(null); const [amount,setAmount]=useState(1000); const [role,setRole]=useState('Donor');
 const visible=useMemo(()=>campaigns.filter(c=>(filter==='All'||c.category===filter)&&(`${c.title} ${c.location} ${c.category}`).toLowerCase().includes(search.toLowerCase())),[filter,search]);
 const toggleTheme=()=>{const d=!dark;setDark(d);document.documentElement.classList.toggle('dark',d);localStorage.setItem('kvd-theme',d?'dark':'light')};
 return <div className="app">
  <header className="nav"><a className="brand" href="#top"><span className="logo"><Heart size={17} fill="currentColor"/></span><span>KVD<small>Kindred Vince Donations</small></span></a><nav className={menu?'open':''}><a href="#campaigns">Campaigns</a><a href="#impact">Impact</a><a href="#volunteer">Volunteer</a><a href="#dashboard">Dashboard</a></nav><div className="nav-actions"><button className="icon" onClick={toggleTheme}>{dark?<Sun/>:<Moon/>}</button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><button className="primary compact" onClick={()=>setDonate(campaigns[0])}>Donate <ArrowRight size={16}/></button></div></header>
  <main id="top">
   <section className="hero"><div className="hero-copy"><span className="pill"><ShieldCheck size={15}/> Trusted giving platform</span><h1>Give with purpose.<br/><em>See the impact.</em></h1><p>KVD connects generous people with verified causes across Kenya — with transparent campaigns, secure donations and measurable impact.</p><div className="actions"><button className="primary" onClick={()=>document.getElementById('campaigns').scrollIntoView()}>Explore campaigns <ArrowRight/></button><button className="secondary" onClick={()=>setRole('Charity')}>Start a campaign</button></div><div className="trust"><span><ShieldCheck/> Verified organizations</span><span><Receipt/> Transparent receipts</span></div></div><div className="hero-card"><div className="hero-glow"/><div className="floating"><span>Community impact</span><strong>KES 18.4M</strong><small>raised through KVD</small><div className="avatars"><i>J</i><i>A</i><i>M</i><i>+</i></div></div><div className="impact-ring"><Heart fill="currentColor"/></div></div></section>
   <section className="stats"><div><TrendingUp/><strong>KES 18.4M</strong><span>Raised</span></div><div><Users/><strong>12,640</strong><span>Donors</span></div><div><ShieldCheck/><strong>186</strong><span>Verified campaigns</span></div><div><HandHeart/><strong>94%</strong><span>Impact delivery</span></div></section>
   <section className="section" id="campaigns"><div className="section-head"><div><span className="eyebrow">CAUSES WORTH CARING ABOUT</span><h2>Find a campaign close to your heart.</h2></div><div className="search"><Search size={17}/><input placeholder="Search campaigns..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="filters">{['All','Education','Healthcare','Food','Environment'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="grid">{visible.map(c=><article className="campaign" key={c.id}><div className={`cover c${c.id}`}><span><ShieldCheck size={13}/> Verified</span><b>{c.category}</b></div><div className="body"><div className="location"><MapPin size={14}/>{c.location}<span>• {c.days} days left</span></div><h3>{c.title}</h3><p>{c.desc}</p><div className="bar"><i style={{width:`${Math.min(100,c.raised/c.goal*100)}%`}}/></div><div className="meta"><strong>{kes(c.raised)}</strong><span>of {kes(c.goal)}</span><b>{Math.round(c.raised/c.goal*100)}%</b></div><div className="bottom"><span>{c.donors} supporters</span><button onClick={()=>setDonate(c)}>Donate <ArrowRight size={14}/></button></div></div></article>)}</div></section>
   <section className="section impact" id="impact"><div className="section-head"><div><span className="eyebrow">TRANSPARENT IMPACT</span><h2>Every contribution tells a story.</h2></div><span className="live"><i/> Live platform data</span></div><div className="analytics"><div className="chart"><ResponsiveContainer width="100%" height={300}><BarChart data={chart}><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="amount" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div><div className="impact-list"><div><strong>1,840</strong><span>students supported</span></div><div><strong>420</strong><span>families reached</span></div><div><strong>37</strong><span>community projects</span></div><div><strong>12.6k</strong><span>volunteer hours</span></div></div></div></section>
   <section className="volunteer section" id="volunteer"><div><span className="eyebrow">MAKE TIME MATTER</span><h2>Give more than money.</h2><p>Find verified volunteer opportunities, apply in minutes and track your community contribution.</p><button className="primary">Explore opportunities <ArrowRight/></button></div><div className="vol-card"><Users/><strong>Community Food Drive</strong><span>18 of 20 volunteers needed</span><div className="bar"><i style={{width:'90%'}}/></div><small><MapPin size={13}/> Community Centre · Saturday</small></div></section>
   <section className="dashboard section" id="dashboard"><div className="dash-top"><div><span className="eyebrow">KVD COMMAND CENTRE</span><h2>One platform. Every role.</h2></div><select value={role} onChange={e=>setRole(e.target.value)}><option>Donor</option><option>Charity</option><option>Volunteer</option><option>Administrator</option></select></div><div className="dash-grid"><div className="dash-main"><div className="mini-stats"><div><span>Total donated</span><strong>KES 24,500</strong></div><div><span>Campaigns supported</span><strong>12</strong></div><div><span>Impact score</span><strong>94%</strong></div></div><div className="activity"><div className="row"><span>Education Drive</span><b>KES 2,000</b><small>Successful</small></div><div className="row"><span>Food Relief</span><b>KES 1,500</b><small>Successful</small></div><div className="row"><span>Forest Restoration</span><b>KES 3,000</b><small>Successful</small></div></div></div><aside><LayoutDashboard/><h3>{role} workspace</h3><p>Manage your KVD activity, notifications, receipts and impact from one place.</p><button className="secondary">Open dashboard</button></aside></div></section>
   <section className="cta"><div><span className="eyebrow">BUILD GOOD THINGS</span><h2>Have a cause worth supporting?</h2><p>Organizations can apply for verification and launch transparent fundraising campaigns.</p></div><button className="light" onClick={()=>setRole('Charity')}>Apply as an organization <ArrowRight/></button></section>
  </main><footer><a className="brand" href="#top"><span className="logo"><Heart size={15} fill="currentColor"/></span><span>KVD<small>Kindred Vince Donations</small></span></a><span>© 2026 KVD. Built for impact.</span><span>Privacy · Terms · Safety</span></footer>
  {donate&&<div className="modal-backdrop" onClick={()=>setDonate(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDonate(null)}><X/></button><span className="eyebrow">MAKE AN IMPACT</span><h2>Support {donate.title}</h2><p>Your donation will be recorded securely and a receipt can be generated after payment confirmation.</p><div className="amounts">{[500,1000,2500,5000].map(a=><button className={amount===a?'selected':''} onClick={()=>setAmount(a)} key={a}>{kes(a)}</button>)}</div><input className="custom" type="number" min="10" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><div className="mpesa"><strong>M-Pesa donation</strong><span>Use the configured KVD recipient in the secure payment environment. Never enter your M-Pesa PIN on KVD.</span></div><button className="primary full" onClick={()=>{alert(`Donation of ${kes(amount)} started. Complete payment through the configured KVD M-Pesa flow.`);setDonate(null)}}>Continue donation <ArrowRight/></button></div></div>}
 </div>
}
document.documentElement.classList.toggle('dark',localStorage.getItem('kvd-theme')==='dark');
createRoot(document.getElementById('root')).render(<App/>);
